name:                optitest
version:             0.1.0.0
github:              "githubuser/optitest"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/optitest#readme>

dependencies:
- base >= 4.7 && < 5
- wreq >= 0.5.2.1 && < 0.6
- http-types >= 0.9.1 && < 1.0
- http-conduit >= 2.3 && < 3.0
- lens >= 4.16
- lens-aeson >= 1.0.2 && < 1.1
- aeson >= 1.3 && < 1.4
- QuickCheck >= 2.8 && < 3.0
- text


library:
  source-dirs: src

executables:
  optitest-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - optitest

tests:
  optitest-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - optitest
